### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by kevizali** [zach-zhiling-zheng/ChatGPT_Chemistry_Assistant#3]
Hello zach-zhiling-zheng,

First of all, thank you for your contribution.

I am facing 'RateLimitError' when i enter my API.

Is it necessary to upgrade my OpenAI account? If yes, which plan would be suitable? (will Tier 1 plan help?)

Thank you.

**Comment by zach-zhiling-zheng** [comment]
Thank you for your question.

Yes, Tier 1 is sufficient. 

https://platform.openai.com/docs/guides/rate-limits/overview
